config/routes.rb
Rails.application.routes.draw do
resources :jobs

root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, presence: true
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

def index
	respond_to do |format|
    	format.html
    	format.json { render json: JobsDatatable.new(view_context) }
		# @jobs = Job.all
	end
end

def new
	@job = Job.new
end

def create
	job = Job.create(job_params)
	if job.errors.present?
		flash[:errors] = job.errors.full_messages
	else
		flash[:success] = 'Job Created!'
	end
	redirect_to jobs_path
end

def edit
	@job = Job.find(params[:id])
end

def update
	@job = Job.find(params[:id])
	@job.update_attributes(job_params)
	redirect_to jobs_path
end

def show
	@job = Job.find(params[:id])
end

def destroy
	@job = Job.find(params[:id])
	@job.destroy
	redirect_to jobs_path
end

private

def job_params
  params.require(:job).permit(:title, :description, :location)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>

<%#= render "form" %>

<!-- <form class="new_job" id="new_job" action="/jobs" method="post">
  <div>
    <label for="job_title">Title</label>
    <input class="form-control" type="text" name="job[title]" id="job_title" />
  </div>
  <div>
    <label for="job_description">Description</label>
    <textarea class="form-control" name="job[description]" id="job_description" cols="60" rows="6">
</textarea>
  </div>
  <div>
    <label for="job_location">Location</label>
    <input class="form-control" type="text" name="job[location]" id="job_location" />
  </div>
  <br>
  <div>
    <input class="btn btn-primary" type="submit" name="commit" value="Create Job" />
  </div>
</form> -->

<%= form_for :job, :method => 'patch', :url => { :action => 'update' } do |f| %>
  Title: <%= f.text_field :title, class: 'form-control'%><br />
  Location: <%= f.text_field :location, class: 'form-control' %><br />
  Description : <%= f.text_area :description, class: 'form-control' %><br />
  <%= f.submit "Submit", class: 'btn btn-primary' %>

<% end %>

app/views/jobs/index.html.erb
<h1>SF Bay Area Open Jobs</h1>

<% if flash['errors'] %>
	<% flash['errors'].each do |error| %>
		<%= content_tag :div, error, class: "bg-danger" %>
	<% end %>
	<br>
<% elsif flash['success'] %>
	<%= content_tag :div, flash['success'], class: "bg-success" %>
	<br>
<% end %>

<table id="jobs" class="table" data-source="<%= jobs_url(format: "json") %>">
<thead>
    <tr>
      <th>Job Title</th>
      <th>Job Description</th>
      <th>Location</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1>Add a job</h1>

<%#= render "form" %>

<!-- <form class="new_job" id="new_job" action="/jobs" method="post">
  <div>
    <label for="job_title">Title</label>
    <input class="form-control" type="text" name="job[title]" id="job_title" />
  </div>
  <div>
    <label for="job_description">Description</label>
    <textarea class="form-control" name="job[description]" id="job_description" cols="60" rows="6">
</textarea>
  </div>
  <div>
    <label for="job_location">Location</label>
    <input class="form-control" type="text" name="job[location]" id="job_location" />
  </div>
  <br>
  <div>
    <input class="btn btn-primary" type="submit" name="commit" value="Create Job" />
  </div>
</form> -->

<%= form_for :job, :url => { :action => 'create' } do |f| %>
  Title: <%= f.text_field :title, class: 'form-control'%><br />
  Location: <%= f.text_field :location, class: 'form-control' %><br />
  Description : <%= f.text_area :description, class: 'form-control' %><br />
  <%= f.submit "Submit", class: 'btn btn-primary' %>

<% end %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>

  <p><%= @job.description %></p>
  <p><%= @job.location %></p>
  <h5><%= button_to "Edit Posting", edit_job_path(@job), method: :get, class: "btn btn-info"%> </h5>
  <h5><%= button_to 'Delete Posting', @job, method: :delete, class: "btn btn-danger"%> </h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <%= csrf_meta_tags %>
</head>
<body>

<header class='clearfix'>
  <div class="left-nav">
    <ul>
      <li><%= link_to "Home", jobs_path %></li>
    </ul>
  </div>
  <div class="right-nav">
    <ul>
      <li><%= link_to "Add Job", new_job_path %></li>
    </ul>
  </div>
</header>

<div class='content'>
  <%= yield %>
</div>	

</body>
</html>